services:
  nginx:
    image: ghcr.io/incognito124/deploy-test:latest
    container_name: nginx-test
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`test.msmetko.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=le"
    expose:
      - "80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
