services:
  nginx:
    image: my-nginx
    container_name: nginx-test
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx_network"
      - "traefik.http.routers.nginx.rule=Host(`test.msmetko.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=le"
    expose:
      - "80"
    networks:
      - traefik_default

networks:
  nginx_network: {}
