name: Trigger action
on:
  push:
    branches:
      - master
jobs:
  action:
    name: Deploy action
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy ansible
        uses: InCogNiTo124/scaling-lamp@master
        with:
          vault-password: ${{ secrets.VAULT_PASSWORD }}
